on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-docker:
    name: Création de l'image Docker
    runs-on: ubuntu-22.04 #Mettre ubuntu-latest revient au même
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and Push Docker images to Github Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/troctaplante/troctaplante-api:production
